dist: xenial
language: python
python:
    - "3.7"
    - "3.7-dev"  # 3.7 development branch
    - "3.8-dev"  # 3.8 development branch
    - "nightly"  # nightly build
install:
    - 'pip install pipenv'
    - 'pipenv install --dev'
script:
    - pytest --cov=aiocrawler
after_success:
    - coveralls
notifications:
    email:
        recipients:
            - tapan.pandita@gmail.com
        on_success: change
        on_failure: always
branches:
    only:
        - master
        - develop
